name: CI
    
on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Configurar Python
              uses: actions/setup-python@v7

            - name: Instalar dependencias
              run: pip install -r requirements.txt

            - name: Run tests
              run: python -m pytest

    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 
              uses: actions/checkout@v4

            - name: Configurar Python
              uses: actions/setup-python@v7
              with:
                python-version: '3.12'

            - name: Instalar Ruff
              run: pip install ruff

            - name: lint check
              run: ruff check .

    build:
        needs: 
            - test
            - lint
        
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout 
              uses: actions/checkout@v4

            - name: AWS access
              uses: aws-actions/configure-aws-credentials@v6
              with:
                aws-access-key-id: ${{secrets.KEY_ID_AWS}}
                aws-secret-access-key: ${{secrets.ACCESS_KEY_AWS}}
                aws-region: ${{secrets.AWS_REGION}}

